### ISSUE TITLE
How to create a database from scratch?

### ISSUE THREAD

**Issue by dpisarenko** [lehvolk/xodus-entity-browser#9]
I want to create some entity stores. For this purpose I try to setup it by entering some existing path in the "location" field and a property name in the "key" field. When I submit the form I get the error "There is no entity types in Xodus store. Try setup another one".

How can I create a new entity store?

**Comment by lehvolk** [comment]
@dpisarenko by opening a store with a new key you create one but without entity types.

> How can I create a new entity store?

You have created empty store but you can't edit it in UI. The only thing needed from UI is creating new entity type. I'll implement this.

**Comment by lehvolk** [comment]
I've added ability to create entity types in UI

**Comment by dpisarenko** [comment]
Thanks!
